%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Andrea TL\Documents\MATLAB\simulateur_vo\upcPrice.txt
%
% Auto-generated by MATLAB on 07-Apr-2022 22:00:07

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "ML", "NELSONSSPRING", "VarName4", "Var5", "Var6"];
opts.SelectedVariableNames = ["VarName1", "ML", "NELSONSSPRING", "VarName4"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["VarName1", "ML", "NELSONSSPRING", "VarName4", "Var5", "Var6"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["VarName1", "ML", "NELSONSSPRING", "VarName4", "Var5", "Var6"], "EmptyFieldRule", "auto");

% Import the data
upcPrice1 = readmatrix("upcPrice.txt", opts);


%% Clear temporary variables
clear opts